apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  type: LoadBalancer
  selector:
    component: web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30001